schema_version: 1

context:
  version: "1.2.0"
  name: omfiles

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ca42ebb260de73e937cb4a72d1867e34e7046f19105202c01d1455c72abf6895

build:
  number: 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - clangdev
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1.7,<2.0
  host:
    - python
    - maturin >=1.7,<2.0
    - pip
    - puccinialin
  run:
    - python
    - numpy >=1.21.0

tests:
  - python:
      imports:
        - omfiles
      pip_check: true

about:
  summary: Python bindings for the Open-Meteo file format
  license: GPL-2.0-only
  license_file: LICENSE
  homepage: https://github.com/open-meteo/python-omfiles

extra:
  recipe-maintainers:
    - terraputix
    - akrherz
